### ISSUE TITLE
No module named models.rnn.translate

### ISSUE THREAD

**Issue by kunal14053** [dashayushman/deep-trans#8]
Traceback (most recent call last):
  File "transliterate.py", line 32, in <module>
    import seq2seq_model
  File "/data/home/kunal/Desktop/ML-Project/deep-trans/seq2seq_model.py", line 14, in <module>
    from tensorflow.models.rnn.translate import data_utils 
ImportError: No module named models.rnn.translate

**Comment by Ribhavs54** [comment]
try downgrading to tensorflow version 0.12.1
